name = "ed-tunnel-worker"  # Имя вашего Worker
main = "_worker.js"
compatibility_date = "2023-10-01"  # Актуальная дата для совместимости

[vars]
UUID = "your-uuid-here"  # Замените на ваш UUID, например: "43aad578-2139-4983-b4eb-94680042b8f7"
# Для нескольких UUID: UUID = "uuid1,uuid2,uuid3" (через запятую, без пробелов)
# Опционально: ProxyIP для маршрутизации через прокси (IP или домен, чтобы избежать блокировок Cloudflare IP)
PROXYIP = ""  # Оставьте пустым, если не нужно. Пример: "1.1.1.1" или "proxy.example.com"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea,89b64978-6244-4bf3-bf64-67ade4ce5c8f,d342d11e-d424-4583-b36e-524ab1f0afa4"
